# Generated by Django 5.0.6 on 2024-07-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField()),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fee_date', models.DateField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='memeber_pictures/')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Non Active', 'Non Active')], default='Active', max_length=10)),
            ],
        ),
    ]
