# Generated by Django 5.0.6 on 2024-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='fee_status',
            field=models.CharField(choices=[('Due', 'Due'), ('Paid', 'Paid')], default='Paid', max_length=10),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='phone_no',
            field=models.CharField(max_length=100),
        ),
    ]
